CREATE SCHEMA IF NOT EXISTS explore_statistics;

CREATE TABLE IF NOT EXISTS explore_statistics.hit (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app varchar NOT NULL,
    uri varchar NOT NULL,
    ip varchar NOT NULL,
    time_stamp timestamp NOT NULL
);
