server:
  port: 9090
spring:
  banner:
    location: banner-stat.txt
  application:
    name: statistics-server
  datasource:
    url: "jdbc:postgresql://localhost:5432/statistics"
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      schema: explore_statistics
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: explore_statistics
    show-sql: ${JPA_SHOW_SQL:true}
  flyway:
    enabled: true
    validate-on-migrate: true
logging:
  level:
    root: INFO
